export const Menuitems =[
    {
        title:"Home",
        url:"/",
        cName:"nav-links"
    },
    {
        title:"About",
        url:"/About",
        cName:"nav-links"
    },
    {
        title:"Services",
        url:"/Services",
        cName:"nav-links"
    },
    {
        title:"Contact",
        url:"/Contact",
        cName:"nav-links"
    },
    {
        title:"SignUp",
        url:"/Signup",
        cName:"nav-links"
    },
]